### ISSUE TITLE
Error while generating fonts. : no script for preionic2-custom-icons, continuing

### ISSUE THREAD

**Issue by darmie** [GerritErpenstein/ionic2-custom-icons#16]
I followed all instructions in the Readme. But I can't get past this error:

```
[19:48:25] ionic2-custom-icons: Creating custom icon set 'adroyticons'
[19:48:25] gulp-svgicons2svgfont: Font created

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Damilare\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic2-custom-icons"
npm ERR! node v4.2.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! adroyte-mvs@ ionic2-custom-icons: `ionic2-custom-icons`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the adroyte-mvs@ ionic2-custom-icons script 'ionic2-custom-icons'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the adroyte-mvs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic2-custom-icons
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs adroyte-mvs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls adroyte-mvs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Damilare\RemoteJob\Adroyte\dev\MVS\npm-debug.log

```

verbose npm debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Damilare\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic2-custom-icons' ]
2 info using npm@4.0.3
3 info using node@v4.2.1
4 verbose run-script [ 'preionic2-custom-icons',
4 verbose run-script   'ionic2-custom-icons',
4 verbose run-script   'postionic2-custom-icons' ]
5 info lifecycle adroyte-mvs@~preionic2-custom-icons: adroyte-mvs@
6 silly lifecycle adroyte-mvs@~preionic2-custom-icons: no script for preionic2-custom-icons, continuing
7 info lifecycle adroyte-mvs@~ionic2-custom-icons: adroyte-mvs@
8 verbose lifecycle adroyte-mvs@~ionic2-custom-icons: unsafe-perm in lifecycle true
9 verbose lifecycle adroyte-mvs@~ionic2-custom-icons: PATH:C:\Users\Damilare\AppData\Roaming\nvm;C:\Program Files\nodejs
10 verbose lifecycle adroyte-mvs@~ionic2-custom-icons: CWD: C:\Users\Damilare\RemoteJob\Adroyte\dev\MVS
11 silly lifecycle adroyte-mvs@~ionic2-custom-icons: Args: [ '/d /s /c', 'ionic2-custom-icons' ]
12 silly lifecycle adroyte-mvs@~ionic2-custom-icons: Returned: code: 3221226356  signal: null
13 info lifecycle adroyte-mvs@~ionic2-custom-icons: Failed to exec ionic2-custom-icons script
14 verbose stack Error: adroyte-mvs@ ionic2-custom-icons: `ionic2-custom-icons`
14 verbose stack Exit status 3221226356
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Damilare\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Damilare\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid adroyte-mvs@
16 verbose cwd C:\Users\Damilare\RemoteJob\Adroyte\dev\MVS
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Damilare\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic2-custom-icons"
19 error node v4.2.1
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error adroyte-mvs@ ionic2-custom-icons: `ionic2-custom-icons`
22 error Exit status 3221226356
23 error Failed at the adroyte-mvs@ ionic2-custom-icons script 'ionic2-custom-icons'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the adroyte-mvs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic2-custom-icons
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs adroyte-mvs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls adroyte-mvs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by darmie** [comment]
Fixed by removing `-` in svg file names.

**Comment by darmie** [comment]
Problem persists... It worked for a while.. now it has stopped again!

**Comment by GerritErpenstein** [comment]
Hi @darmie! Thanks for the report. Can you please try to build the example app and see if it works for you?
https://github.com/GerritErpenstein/ionic2-custom-icons-example

**Comment by darmie** [comment]
Let me try and get back to you.

**Comment by darmie** [comment]
It's not failing on the sample project.

**Comment by darmie** [comment]
I suspect a memory issue, it works for my project sometimes, and it doesn't some other time.
